### ISSUE TITLE
OSError: No wkhtmltopdf executable found: "b''" If this file exists please check that this process can read it.

### ISSUE THREAD

**Issue by AkshatRepo** [kgediya/certio-chain#1]
shows  this error
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\certio-chain-master\app\views.py", line 222, in submit_textarea
    pdfkit.from_string(body,"app/out.pdf")
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pdfkit\api.py", line 70, in from_string
    configuration=configuration, cover_first=cover_first)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pdfkit\pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pdfkit\configuration.py", line 27, in __init__
    'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

after clicking on post in browser(localhost:5000)
I think the problem is in @app.route('/submit', methods=['POST'])

**Comment by AkshatRepo** [comment]
Issue Solved

**Comment by hrpalmaen** [comment]
Buen día

¿Como se soluciono el problema?
